apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-vpce-operator
rules:
  - apiGroups:
    - config.openshift.io
    resources:
    - infrastructures
    - dnses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - aws.managed.openshift.io
    resources:
    - accounts
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - avo.openshift.io
    resources:
    - vpcendpoints
    - vpcendpointacceptances
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
      - avo.openshift.io
    resources:
      - vpcendpoints/status
      - vpcendpointacceptances/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - avo.openshift.io
    resources:
      - vpcendpoints/finalizers
      - vpcendpointacceptances/finalizers
    verbs:
      - update
  - apiGroups:
    - ""
    resources:
    - services
    - services/finalizers
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
