apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-vpce-operator-override-secret
  namespace: openshift-aws-vpce-operator
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
