apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-vpce-operator-override-secret
  namespace: openshift-aws-vpce-operator
subjects:
  - kind: ServiceAccount
    name: aws-vpce-operator
    namespace: openshift-aws-vpce-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-vpce-operator-override-secret
